name: GitHub Repo Export

on:
  workflow_dispatch:     # Allows manual trigger from GitHub UI
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at 00:00 UTC, change as needed

jobs:
  export_repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'   # Use latest 3.x available

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests openpyxl

    - name: Run repo export script
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        python scan_repos.py
